module.exports= {
    ADD_QUERY:'ADD_QUERY',
    ADD_KWARGS:'ADD_KWARGS',
    REMOVE_PROPS_NAME:'REMOVE_PROPS_NAME',
    ADD_CHAT:'ADD_CHAT',
    REMOVE_LINK:'REMOVE_LINK',
    ADD_INDICATOR:'ADD_INDICATOR',
    ADD_LINK:'ADD_LINK',
    REMOVE_INDICATOR:'REMOVE_INDICATOR',
    ADD_PROPS_NAME:'ADD_PROPS_NAME',
    ADD_CHAT:'ADD_CHAT',
    CLEAR_QUERY:'CLEAR_QUERY',
    ADD_QA:'ADD_QA',
    UPDATE_USER:'UPDATE_USER',
    ADD_SUGGESTIONS:'ADD_SUGGESTIONS',
    CLEAR_SUGGESTIONS:'CLEAR_SUGGESTIONS',
    UPDATE_AUTH:'UPDATE_AUTH',
    

}